spring:
  datasource:
    url: jdbc:mysql://localhost:3306/check_if
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: checkif.tcc@gmail.com
    password: wlcreidcqnqdtfvj
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  error:
    include-message: always

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.servlet: DEBUG
    #org.springframework.security: DEBUG